services:
  homepage:
    image: ghcr.io/gethomepage/homepage
    container_name: homepage
    environment:
      HOMEPAGE_ALLOWED_HOSTS: "*"
    ports:
      - "3010:3000"
    volumes:
      - ${CONFIG_ROOT}/homepage:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped