---
all:
  children:
    proxmox:
      hosts:
        srv-pve-01:
          ansible_user: root
          ansible_host: srv-pve-01.home.arpa
        srv-pve-02:
          ansible_user: root
          ansible_host: srv-pve-02.home.arpa
    core:
      hosts:
        srv-core-01:
          ansible_user: sysadmin
          ansible_host: srv-core-01.home.arpa
    compute:
      hosts:
        srv-compute-01:
          ansible_user: sysadmin
          ansible_host: srv-compute-01.home.arpa
