---
all:
  children:
    server:
      hosts:
        srv-core-01:
          ansible_user: sysadmin
          ansible_host: srv-core-01.home.arpa
          ansible_python_interpreter: /usr/bin/python3.13
        srv-stage-01:
          ansible_user: sysadmin
          ansible_host: srv-stage-01.home.arpa
          ansible_python_interpreter: /usr/bin/python3.13
        srv-rpi-01:
          ansible_user: sysadmin
          ansible_host: srv-rpi-01.home.arpa
          ansible_python_interpreter: /usr/bin/python3.13
