services:

  shairport-sync:
    image: mikebrady/shairport-sync:5.2
    container_name: shaiport-sync
    network_mode: host
    restart: unless-stopped
    devices:
      - /dev/snd:/dev/snd
    command:
      - "-a"
      - "Panasonic SC-PMX90"
      - "--"
      - "-d"
      - "plughw:0,0"
      - "-c"
      - "Master"
