---
- name: Install ubuntu-drivers utility
  ansible.builtin.apt:
    name: ubuntu-drivers-common
    state: present
    update_cache: yes

- name: Install NVIDIA drivers
  ansible.builtin.command:
    cmd: "ubuntu-drivers install --gpgpu"
  register: nvidia_driver
  changed_when: "'No drivers found' not in nvidia_driver.stdout"

- name: Install NVIDIA utilities
  ansible.builtin.shell:
    cmd: |
      version=$(dpkg -l | grep -Po 'nvidia-driver-\K[0-9]+' | head -1)
      apt install -y nvidia-utils-${version}-server
  changed_when: true
  when: nvidia_driver is changed

- name: Install nvidia-container-toolkit
  ansible.builtin.apt:
    name: nvidia-container-toolkit
    state: present
  when: nvidia_driver is changed

- name: Reboot to load NVIDIA kernel modules
  ansible.builtin.reboot:
    reboot_timeout: 300
  when:
    - nvidia_driver_reboot | bool
    - nvidia_driver is changed
