services:

  isponsorblocktv:
    image: ghcr.io/dmunozv04/isponsorblocktv:v2.10.0
    container_name: isponsorblocktv
    restart: unless-stopped
    volumes:
      - ${CONFIG_ROOT}/isponsorblocktv:/app/data