services:

  openwebui:
    image: ghcr.io/open-webui/open-webui:v0.10.2-slim
    container_name: open-webui
    restart: unless-stopped
    ports:
      - "3011:8080"
    volumes:
      - ${CONFIG_ROOT}/open-webui:/app/backend/data
