name: Check for image updates

on:
  schedule:
    - cron: '0 3 * * 0'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update-images:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.1

      - uses: regclient/actions/regctl-installer@main

      - name: Check for updates
        run: python3 .github/scripts/check-updates.py

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v8.1.1
        with:
          commit-message: 'chore(images): update docker image tags'
          title: 'chore(images): update docker image tags'
          branch: auto/image-updates
          branch-suffix: timestamp
          delete-branch: true
